all:
  children:
    dc:
      hosts:
        samba-ad-dc:
          ansible_host: 192.168.56.5
          ansible_user: vagrant
          ansible_become: true
          ansible_private_key_file: /home/kevin/Test-samba-ad-dc/.vagrant/machines/default/virtualbox/private_key
