---
- name: Installer Bind9
  ansible.builtin.package:
    name: bind9
    state: present

- name: Créer le dossier des zones
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    mode: '0755'

- name: Copier named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Copier named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Générer la zone DNS forward
  ansible.builtin.template:
    src: db.forward.j2
    dest: "/etc/bind/zones/db.{{ dns_domain }}"
  notify: Restart bind9

- name: Générer la zone DNS reverse
  ansible.builtin.template:
    src: db.reverse.j2
    dest: "/etc/bind/zones/db.{{ dns_reverse_zone }}"
  notify: Restart bind9

- name: Activer et démarrer Bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
