---
# 1. Créer le dossier du runner
- name: Créer le dossier du runner
  file:
    path: "{{ gitlab_runner_path }}/config"
    state: directory
    mode: '0755'
    recurse: true

# 2. Déployer un config.toml minimal
- name: Déployer un config.toml minimal
  template:
    src: config.toml.j2
    dest: "{{ gitlab_runner_path }}/config/config.toml"
    mode: '0644'

# 3. Corriger les permissions
- name: Corriger les permissions du runner
  file:
    path: "{{ gitlab_runner_path }}/config"
    owner: 1000
    group: 1000
    recurse: true

# 4. Créer le conteneur GitLab Runner
- name: Créer le conteneur GitLab Runner
  community.docker.docker_container:
    name: "{{ gitlab_runner_name }}"
    image: "gitlab/gitlab-runner:{{ gitlab_runner_version }}"
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ gitlab_runner_path }}/config:/etc/gitlab-runner"
    state: started
