---
- name: Créer dossier d'installation Wiki.js
  file:
    path: "{{ wikijs_install_dir }}"
    state: directory
    mode: "0755"

- name: Déployer docker-compose.yml pour Wiki.js
  template:
    src: docker-compose.yml.j2
    dest: "{{ wikijs_install_dir }}/docker-compose.yml"
    mode: "0644"

- name: Démarrer la stack Wiki.js
  community.docker.docker_compose_v2:
    project_src: "{{ wikijs_install_dir }}"
    state: present

