---
# Domaine principal
reverse_proxy_domain: "kevin.lan"

# Port par défaut si non spécifié
reverse_proxy_default_port: 80

# Ports personnalisés pour certains services
reverse_proxy_overrides:
  grafana: 3000
  prometheus: 9090
  alertmanager: 9093
  snmp-exporter: 9116

# Alias → service réel
reverse_proxy_aliases:
  snmp: grafana

# Certificats
reverse_proxy_cert_days: 3650
reverse_proxy_country: "FR"
reverse_proxy_state: "Occitanie"
reverse_proxy_locality: "Montpellier"
reverse_proxy_org: "Kevin"
reverse_proxy_ou: "IT"
