---
harbor_version: "v2.14.2"

harbor_data_dir: "/data/harbor"

harbor_db_password: "root123"
harbor_redis_password: "redis123"

harbor_cert_days: 3650
harbor_country: "FR"
harbor_state: "PACA"
harbor_locality: "Marseille"
harbor_org: "greencontracts"
harbor_ou: "IT"

hostname: "greencontracts.org"
nginx_external_port: 443
harbor_internal_port: 80
tls_terminated_by_nginx: true

cert_path: "/etc/nginx/certs/wildcard.kevin.lan.crt"
key_path: "/etc/nginx/certs/wildcard.kevin.lan.key"

harbor_admin_password: "Harbor12345"

enable_trivy: true
enable_notary: false
enable_chartmuseum: false

install_docker: true
docker_user: "ubuntu"

harbor_install_dir: "/opt/harbor"

# IMPORTANT : "latest" n'est pas gérable automatiquement par Ansible.
# Je te mets la dernière version stable connue.
#harbor_version: "v2.12.0"

harbor_installer_filename: "harbor-online-installer-{{ harbor_version }}.tgz"
harbor_download_url: "https://github.com/goharbor/harbor/releases/download/{{ harbor_version }}/{{ harbor_installer_filename }}"
