---
# 6️⃣ Installer Nginx
- name: "6 - Installer Nginx"
  ansible.builtin.apt:
    name: nginx
    state: present

# 7️⃣ Déployer la conf Nginx
- name: "7 - Déployer la configuration Nginx"
  ansible.builtin.template:
    src: nginx-modoboa.conf.j2
    dest: /etc/nginx/sites-available/modoboa.conf

# 8️⃣ Activer le site
- name: "8 - Activer le site"
  ansible.builtin.file:
    src: /etc/nginx/sites-available/modoboa.conf
    dest: /etc/nginx/sites-enabled/modoboa.conf
    state: link
    force: yes

# 9️⃣ Redémarrer Nginx
- name: "9 - Redémarrer Nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
