# Version de GitLab CE
gitlab_version: "latest"

# Version du runner (utilisé uniquement si tu gardes un runner dans ce rôle)
gitlab_runner_version: "latest"

# Nom DNS du GitLab
gitlab_hostname: "gitlab.kevin.lan"

# Ports exposés
gitlab_http_port: "80"
gitlab_ssh_port: "2222"

# Chemin où sera stocké le docker-compose et les données GitLab
gitlab_compose_path: "/opt/gitlab"

# Réseau Docker utilisé par GitLab
gitlab_network_name: "gitlab-network"

# Runner supplémentaire (désactivé par défaut)
gitlab_additional_runner: false
runner_id: "2"

