---
- name: Installer dépendances
  apt:
    name:
      - curl
      - ca-certificates
      - tzdata
      - perl
    state: present
    update_cache: yes

- name: Ajouter le dépôt GitLab
  shell: |
    curl -s {{ gitlab_repo_script }} | bash
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

- name: Installer GitLab CE
  apt:
    name: "{{ gitlab_package }}"
    state: present

- name: Déployer la configuration GitLab
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  notify: Reconfigure GitLab

- name: Forcer la reconfiguration initiale
  command: gitlab-ctl reconfigure
  when: gitlab_force_reconfigure | default(true)
