---
- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/prometheus
    - /opt/prometheus/config
    - /opt/prometheus/data

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/config/prometheus.yml

- name: Fix permissions on Prometheus data directory
  file:
    path: /opt/prometheus/data
    owner: 65534
    group: 65534
    recurse: yes

- name: Run Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart_policy: always
    networks:
      - name: monitoring
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/prometheus/data:/prometheus
