---
###############################################################################
# DNS Registry
#
# Objectif :
# - Vérifier si les entrées DNS existent
# - Créer uniquement les entrées manquantes
# - Toutes les entrées pointent vers le reverse proxy
###############################################################################

- name: Obtenir un ticket Kerberos pour Administrator
  ansible.builtin.command: "kinit administrator@{{ dns_domain | upper }}"
  args:
    stdin: "{{ samba_admin_password }}"
  changed_when: false


###############################################################################
# Vérification des entrées DNS existantes
###############################################################################

- name: Vérifier si l’enregistrement DNS existe
  ansible.builtin.command:
    cmd: "dig +short @127.0.0.1 {{ item }} A"
  register: dns_query
  changed_when: false
  loop: "{{ dns_entries }}"

###############################################################################
# Création des entrées DNS manquantes
###############################################################################

- name: Créer les enregistrements DNS manquants
  ansible.builtin.include_tasks: create_record.yml
  loop: "{{ dns_entries }}"
  loop_control:
    index_var: record_index