# Dockerfile personnalisé Beszel avec outils de diagnostic
FROM henrygd/beszel:{{ beszel_base_tag }} as beszel-base

FROM alpine:{{ beszel_alpine_tag }}

RUN apk add --no-cache \
    bash \
    curl \
    busybox-extras \
    bind-tools

COPY --from=beszel-base /beszel /beszel

EXPOSE {{ beszel_port }}

ENTRYPOINT ["/beszel"]
CMD ["serve", "--http=0.0.0.0:{{ beszel_port }}"]
