---
galaxy_info:
  author: Kevin DANIEL
  description: Déploiement Wiki.js avec PostgreSQL distant
  company: homelab

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: ubuntu
      versions:
        - 24.04


collections:
  - community.docker
  - community.postgresql