---
- name: Déploiement de GitLab
  hosts: gitlab
  become: yes
  roles:
    - gitlab-docker
#    - gitlab
#    - gitlab-runner-docker

# Si deploiement sur machine autre 

#- name: Déploiement des GitLab Runners
#  hosts: runners
#  become: yes
#  roles:
#    - gitlab_runner

