---
- name: Déployer Argo CD sur le cluster k3s
  hosts: k3s_manager
  become: yes
  gather_facts: false

  vars:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  roles:
    - ../roles/argocd
