---
- hosts: dns
  gather_facts: yes
  become: true

  vars:

    ###########################################################################
    # Domaine AD
    ###########################################################################

    dns_domain: "greencontracts.lan"

    ###########################################################################
    # Reverse proxy
    ###########################################################################

    reverse_proxy_ip: "192.168.20.3"

    ###########################################################################
    # Entrées DNS
    ###########################################################################

    dns_entries:
      - proxy.greencontracts.lan
      - moodle.greencontracts.lan
      - argocd.greencontracts.lan
      - wikijs.greencontracts.lan
      - nextcloud.greencontracts.lan
      - mail.greencontracts.lan
      - harbor.greencontracts.lan
      - beszel.greencontracts.lan

  roles:
    - ../roles/dns-server-registry