# ============================================================
# Configuration Mailserver (docker-mailserver)
# ============================================================

mailserver_hostname: "{{ mail_domain | default('mail.' + main_domain) }}"
mailserver_image: "docker.io/mailserver/docker-mailserver:latest"

mailserver_data_dir: "/opt/mailserver/data"
mailserver_config_dir: "/opt/mailserver/config"
mailserver_state_dir: "/opt/mailserver/mail-state"

mailserver_ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"

mailserver_env:
  - "TZ=Europe/Paris"
  - "LOG_LEVEL=info"
  - "SUPERVISOR_LOGLEVEL=info"
  - "SSL_TYPE=manual"
  - "SSL_CERT_PATH=/tmp/docker-mailserver/ssl/cert.pem"
  - "SSL_KEY_PATH=/tmp/docker-mailserver/ssl/key.pem"
  - "PERMIT_DOCKER=connected-networks"
  - "ENABLE_SPAMASSASSIN=1"
  - "ENABLE_CLAMAV=1"
  - "ENABLE_FAIL2BAN=1"
  - "ENABLE_POSTGREY=1"
  - "ENABLE_SASLAUTHD=0"
  - "ONE_DIR=1"
  - "ENABLE_POP3=0"
  - "ENABLE_MANAGESIEVE=1"
  - "POSTFIX_MESSAGE_SIZE_LIMIT=50000000"
  - "ENABLE_QUOTAS=1"
  - "POSTFIX_DSN=0"
  - "ENABLE_UPDATE_CHECK=0"
