Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.hostname = "modoboa"
  config.vm.network "private_network", ip: "192.168.56.30"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.gui = false
    vb.name = "modoboa-vm"    
  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "playbook.yml"
#    ansible.inventory_path = "inventory.yml"
#    ansible.become = true
#    ansible.limit = "modoboa"
#    ansible.verbose = "vvvv"
#  end
end

