---
- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/grafana
    - /opt/grafana/provisioning
    - /opt/grafana/provisioning/datasources

- name: Deploy Grafana datasource
  template:
    src: datasource.yml.j2
    dest: /opt/grafana/provisioning/datasources/prometheus.yml

- name: Fix permissions on Grafana data directory
  file:
    path: /opt/grafana
    owner: 472
    group: 472
    recurse: yes

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    restart_policy: always
    networks:
      - name: monitoring
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana:/var/lib/grafana
      - /opt/grafana/provisioning:/etc/grafana/provisioning
