beszel_agent_enabled: true

beszel_agent_server: "http://127.0.0.1:8090"
beszel_agent_listen_port: "45876"
beszel_agent_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBMMSHHHEPJfZAPIgQO7iivtBhOSNqNZn2fHqSj/zuOR"
beszel_agent_token: "125d3-ca4f7daea-cea56-3e194dc68"
beszel_agent_hub_url: "http://127.0.0.1:8090"
beszel_agent_system_name: "{{ inventory_hostname }}"
beszel_agent_data_dir: "/opt/beszel/agent_data"
beszel_agent_install_dir: "/opt/beszel"


