# Domaine AD
dns_domain: "{{ main_domain }}"

# Nom du DC (doit correspondre à ton inventaire)
dc_hostname: "samba-ad-dc.{{ main_domain }}"

# IP du reverse proxy (unique point d’entrée)
reverse_proxy_ip: "{{ services.reverse_proxy.backend_ip }}"

# Extraction dynamique des FQDN depuis ton inventaire
dns_entries: "{{ services | dict2items | map(attribute='value.fqdn') | list }}"
