---
# 0. Désinstallation des anciennes versions
- name: 0. Supprimer les anciens paquets Docker
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
  ignore_errors: true

# 1. Installation des dépendances système
- name: 1. Installer dépendances système
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

# 2. Création du dossier keyrings
- name: 2. Créer /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# 3. Téléchargement de la clé GPG Docker
- name: 3. Télécharger la clé GPG Docker (format .asc)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ docker_keyring_path }}"
    mode: '0644'

# 4. Création du fichier docker.sources (méthode officielle)
- name: 4. Ajouter le dépôt Docker dans docker.sources
  copy:
    dest: "{{ docker_sources_file }}"
    mode: '0644'
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Signed-By: {{ docker_keyring_path }}

# 4.1 Attendre que le lock APT soit libéré
- name: Attendre que le lock APT soit libéré
  shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      sleep 2
    done
  changed_when: false

# 5. Mise à jour de l’index APT (avec retry)
- name: 5. Mettre à jour apt (retry)
  apt:
    update_cache: yes
  register: apt_update
  retries: 10
  delay: 5
  until: apt_update is succeeded

# 6. Installation de Docker Engine
- name: 6. Installer Docker Engine et plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# 7. Activation du service Docker
- name: 7. Activer et démarrer Docker
  service:
    name: docker
    state: started
    enabled: yes

# 8. Ajout de l’utilisateur au groupe docker
- name: 8. Ajouter utilisateur au groupe docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user is defined
