---
- hosts: dns
  gather_facts: yes
  #become: true


  vars:
    # Variables globales provenant de l'inventaire
    services: "{{ hostvars['localhost'].services | default(hostvars['all'].services) }}"
    main_domain: "{{ hostvars['localhost'].main_domain | default(hostvars['all'].main_domain) }}"

    # Domaine DNS Samba
    dns_domain: "{{ main_domain }}"

    # Hostname du DC Samba
    dc_hostname: "{{ ansible_hostname }}"
    #dc_hostname: "dns-samba-ad" #nom utiliser un refactoring et a prevoir trop d'erreur de nom de variable diferentes
    #dc_hostname: "samba-ad-dc.{{ main_domain }}"

    # Liste dynamique des FQDN à enregistrer
    dns_entries: "{{ services | dict2items | map(attribute='value.fqdn') | list }}"

  roles:
    - ../roles/dns-server-registry

    