Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.network :private_network, ip: "192.168.56.25"
  config.vm.hostname = "openproject"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    vb.gui = true
    vb.name = "open_project"
  end

  # Provision shell classique
  config.vm.provision "shell", path: "provision.sh"
end
