---
- name: Générer le fichier nsupdate
  ansible.builtin.copy:
    dest: "/tmp/nsupdate-{{ item }}.txt"
    content: |
      server 127.0.0.1
      zone {{ dns_domain }}
      update add {{ item }} 3600 A {{ reverse_proxy_ip }}
      send
    mode: "0644"
  when: dns_query.results[record_index].stdout == ""

- name: Appliquer la mise à jour DNS via keytab machine
  ansible.builtin.command:
    cmd: "nsupdate -g /tmp/nsupdate-{{ item }}.txt"
  environment:
    KRB5_KTNAME: "/var/lib/samba/private/secrets.keytab"
  when: dns_query.results[record_index].stdout == ""

- name: Supprimer fichier temporaire
  ansible.builtin.file:
    path: "/tmp/nsupdate-{{ item }}.txt"
    state: absent
  when: dns_query.results[record_index].stdout == ""
