beszel_agent_enabled: true

beszel_agent_server: "http://192.168.20.4:8090"
beszel_agent_listen_port: "45876"
# beszel_agent_key et beszel_agent_token sont définis par le rôle beszel_hub_extract
#beszel_agent_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPj5QTJmV8WrwLkuxmQaKFu11ym5PJTdrrt49NbZeVYU"
#beszel_agent_token: "25d15c-74849b8c-4690c2-845ba02"
beszel_agent_hub_url: "http://192.168.20.4:8090"
beszel_agent_system_name: "{{ inventory_hostname }}"
beszel_agent_data_dir: "/opt/beszel/agent_data"
beszel_agent_install_dir: "/opt/beszel"


