---
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Remove resolv.conf symlink if present
  file:
    path: /etc/resolv.conf
    state: absent

- name: Configure resolv.conf to use this DC as DNS
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ samba_bind_listen_ip }}
      search {{ samba_realm | lower }}

- name: Configure Bind9 options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Configure Bind9 Samba DLZ include
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

- name: Ensure bind9 is enabled and started
  systemd:
    name: bind9
    state: started
    enabled: yes
