---
- name: Ensure docker is installed
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: Create Beszel directory
  ansible.builtin.file:
    path: "{{ beszel_install_dir }}"
    state: directory
    mode: "0755"

- name: Deploy templated Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ beszel_install_dir }}/Dockerfile"
    mode: "0644"

- name: Build custom Beszel image
  ansible.builtin.command:
    cmd: docker build -t {{ beszel_image_name }} .
    chdir: "{{ beszel_install_dir }}"
  notify:
    - Stop Beszel
    - Start Beszel

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ beszel_install_dir }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Stop Beszel
    - Start Beszel

- name: Start Beszel stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ beszel_install_dir }}"

 ######### AGENT ############   

#- name: Create Beszel agent data directory
#  ansible.builtin.file:
#    path: "{{ beszel_agent_data_dir }}"
#    state: directory
#    mode: "0755"
#  when: beszel_agent_enabled

#- name: Deploy Beszel agent docker-compose
#  ansible.builtin.template:
#    src: docker-compose-agent.yml.j2
#    dest: "{{ beszel_install_dir }}/docker-compose-agent.yml"
#    mode: "0644"
#  when: beszel_agent_enabled
#  notify:
#    - Stop Beszel
#    - Start Beszel

#- name: Start Beszel agent
#  ansible.builtin.command:
#    cmd: docker compose -f docker-compose-agent.yml up -d
#    chdir: "{{ beszel_install_dir }}"
#  when: beszel_agent_enabled

