---
# Variables spécifiques au master
node_id: 1
node_name: node1
is_primary: true
role: master

# Configuration spécifique master
postgresql_config:
  max_wal_senders: 10
  max_replication_slots: 10
  
# Ports Vagrant
vagrant:
  forwarded_ports:
    - guest: 5432
      host: 5433
