---
#- import_playbook: deploy_dns.yml # intégrer avec samba-ad juste rajouter un role de parametrage aprés deploiement de toutes les machine
#- import_playbook: deploy_reverse_proxy.yml # integré au serveur de messagerie stockaga sur nas a parametrer 
- import_playbook: pipeline_cd.yml
- import_playbook: deploy-cluster-db.yml
- import_playbook: deploy-ad-dc.yml # ad & dns ensemble
#- import_playbook: deploy_snmp.yml
- import_playbook: deploy_beszel.yml
- import_playbook: deploy_nextcloud.yml
- import_playbook: deploy_wikijs.yml # voir sur quel autre machine l'intégrer peut etre sur beszel serveur 
- import_playbook: deploy_nds.yml
- import_playbook: deploy_modoboa.yml # en attente de reglages

#- import_playbook: deploy_nextcloud_office.yml
#- import_playbook: deploy_beszel_agents.yml
#- import_playbook: samba-ad-cleanup.yml # nettoyage après déploiement de samba-ad et lui laisse le temps de se stabiliser
# playbook paramtrage ssl / tls / reverse proxy ici
#- import_playbook: deploy_moodle.yml # a ne pas mettre dedans car doit etre deployer ensuite via le script 7-deploy-moodle.sh car il generé une image dans harbor puis deploy dans kubernetes
#- import_playbook: deploy_observability.yml
# playbook paramterage ici