---
#- import_playbook: deploy_dns.yml
- import_playbook: pipeline_cd.yml
- import_playbook: deploy-cluster-db.yml
#- import_playbook: deploy_wikijs.yml
#- import_playbook: deploy_reverse_proxy.yml
#- import_playbook: deploy_snmp.yml

