---
- name: Restart harbor
  ansible.builtin.command:
    cmd: "docker compose up -d"
    chdir: "{{ harbor_install_dir }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

