dns_domain: "kevin.lan"
dns_server_ip: "192.168.200.254"

# Réseau principal
dns_network: "192.168.200"

# Zone inverse PTR
dns_reverse_zone: "200.168.192.in-addr.arpa"

dns_records:
#  - name: "kevin.lan"
#    ip: "192.168.200.253"

  - name: "reverse-proxy.kevin.lan"
    ip: "192.168.200.253"

  - name: "ns.kevin.lan"
    ip: "192.168.200.254"

  - name: "opnsense.kevin.lan"
    ip: "192.168.200.1"

  - name: "management-dk.kevin.lan"
    ip: "192.168.200.2"

  # ... tes autres entrées existantes (harbor, gitlab, etc.)
  - name: "harbor.kevin.lan"
    ip: "192.168.200.50"

  - name: "gitlab.kevin.lan"
    ip: "192.168.200.40"

  - name: "edgedoc.kevin.lan"
    ip: "192.168.200.30"

  - name: "snmp.kevin.lan"
    ip: "192.168.200.20"

  - name: "k3s-manager.kevin.lan"
    ip: "192.168.200.250"

  - name: "k3s-worker1.kevin.lan"
    ip: "192.168.200.251"

  - name: "k3s-worker2.kevin.lan"
    ip: "192.168.200.252"
