---
- hosts: all
  ignore_unreachable: true
  become: yes
  tasks:
    #- docker # sinon prend toute les machines
    - name: Install Docker only on Beszel agent machines
      include_role:
        name: docker
      when: beszel_agent_enabled | default(false) | bool

    - name: Install Beszel agent only on tagged machines
      include_role:
        name: beszel-agent
      when: beszel_agent_enabled | default(false) | bool

    #- role: beszel-agent
    #  when: beszel_agent_enabled | default(false)

