---
- name: Déployer configuration Netplan DNS
  ansible.builtin.template:
    src: netplan-dns.yaml.j2
    dest: "/etc/netplan/50-cloud-init.yaml"
    mode: "0644"

- name: Fix permissions for Netplan file
  ansible.builtin.file:
    path: "/etc/netplan/50-cloud-init.yaml"
    owner: root
    group: root
    mode: "0644"

- name: Appliquer Netplan
  ansible.builtin.command: netplan apply

- name: Redémarrer systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
