---
- name: Stop samba-ad-dc before provisioning
  systemd:
    name: samba-ad-dc
    state: stopped
  when: not samba_provisioned.stat.exists

- name: Provision Samba AD domain (BIND9_DLZ)
  command: >
    samba-tool domain provision
    --domain={{ samba_domain }}
    --realm={{ samba_realm }}
    --adminpass='{{ samba_admin_password }}'
    --server-role=dc
    --use-rfc2307
    --dns-backend=BIND9_DLZ
  args:
    creates: /var/lib/samba/private/sam.ldb
  when: not samba_provisioned.stat.exists
  register: samba_provision_cmd
  notify:
    - restart samba
    - restart bind9

- name: Force Samba to bind only to the correct interface
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE MANAGED INTERFACES"
    insertafter: '^\[global\]'
    block: |
      interfaces = lo {{ samba_interface }}
      bind interfaces only = yes
  when: not samba_provisioned.stat.exists
  notify: restart samba

- name: Copy Kerberos config from Samba
  copy:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    remote_src: yes
  when: not samba_provisioned.stat.exists

#- name: Clean old docker0 DNS A records (172.17.0.1)
#  command: >
#    samba-tool dns delete 127.0.0.1 {{ samba_domain | lower }}.org
#    {{ item.name }} A 172.17.0.1
#    -U administrator%{{ samba_admin_password }}
#  loop:
#    - { name: "dns-samba-ad" }
#    - { name: "@" }
#  ignore_errors: yes
#  when: not samba_provisioned.stat.exists