---
- name: Créer le dossier SSL Nginx
  file:
    path: /etc/nginx/certs
    state: directory
    mode: '0755'

- name: Déployer les certificats Nginx
  vars:
    certs:
      - name: "wildcard.kevin.lan"
      - name: "kevin.lan"
#      - name: "reverse-proxy.kevin.lan"
  block:

    - name: Déployer certificat CRT
      copy:
        src: "{{ cert_store_dir }}/nginx/{{ item.name }}.crt"
        dest: "/etc/nginx/certs/{{ item.name }}.crt"
        mode: '0644'
        force: true
      loop: "{{ certs }}"
      notify: reload nginx

    - name: Déployer clé privée KEY
      copy:
        src: "{{ cert_store_dir }}/nginx/{{ item.name }}.key"
        dest: "/etc/nginx/certs/{{ item.name }}.key"
        mode: '0400'
        force: true
      loop: "{{ certs }}"
      notify: reload nginx

    - name: Déployer fullchain CRT
      copy:
        src: "{{ cert_store_dir }}/nginx/{{ item.name }}-fullchain.crt"
        dest: "/etc/nginx/certs/{{ item.name }}-fullchain.crt"
        mode: '0644'
        force: true
      loop: "{{ certs }}"
      notify: reload nginx

- name: Déployer la CA pour référence
  copy:
    src: "{{ cert_store_dir }}/ca/ca.crt"
    dest: /etc/nginx/certs/ca.crt
    mode: '0644'
    force: true

