---
- hosts: dc
  become: yes
  roles:
    - docker
    - samba-ad-dc

  tasks:
    - name: Attendre que Samba AD DC soit complètement opérationnel
      wait_for:
        port: 389
        host: 127.0.0.1
        delay: 5
        timeout: 60
      tags: wait_samba

    - name: Attendre que DNS Bind9 DLZ soit prêt
      wait_for:
        port: 53
        host: 127.0.0.1
        timeout: 60
      tags: wait_bind9

- hosts: dc
  become: yes
  roles:
    - samba-ad-cleanup
    # - lam
    # - fusiondirectory
