version: "3.8"

services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: moodle

    ports:
      - "8080:80"

    environment:
      # ------------------------------------------------
      # PostgreSQL
      # ------------------------------------------------
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: ${MOODLE_DB_HOST:-192.168.20.20}
      MOODLE_DATABASE_PORT_NUMBER: ${MOODLE_DB_PORT:-5432}
      MOODLE_DATABASE_NAME: ${MOODLE_DB_NAME:-moodle}
      MOODLE_DATABASE_USER: ${MOODLE_DB_USER:-moodle}
      MOODLE_DATABASE_PASSWORD: ${MOODLE_DB_PASSWORD:-motdepasse}

      # ------------------------------------------------
      # Moodle
      # ------------------------------------------------
      MOODLE_WWWROOT: ${MOODLE_WWWROOT:-http://localhost:8080}

      MOODLE_USERNAME: ${MOODLE_ADMIN_USER:-admin}
      MOODLE_PASSWORD: ${MOODLE_ADMIN_PASSWORD:-Admin@123}
      MOODLE_EMAIL: ${MOODLE_ADMIN_EMAIL:-admin@example.com}

      MOODLE_SITE_NAME: ${MOODLE_SITE_NAME:-Moodle 5.2}

    volumes:
      - moodle-data:/var/www/moodledata

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  moodle-data: