---
- name: restart samba
  systemd:
    name: samba-ad-dc
    state: restarted
  when: samba_provisioned.stat.exists | default(false)

- name: restart bind9
  systemd:
    name: bind9
    state: restarted
