---
wikijs_version: "2.5.300"

wikijs_install_dir: "/opt/wikijs"

wikijs_port: 3000

wikijs_app_volume: "wikijs_app_data"

#########################################################
# PostgreSQL distant
#########################################################

wikijs_db_host: "192.168.20.20"
wikijs_db_port: 5432

wikijs_db_name: "wikijs"
wikijs_db_user: "wikijs"
wikijs_db_password: "ChangeMe123"

#########################################################
# Serveur Wiki.js
#########################################################

wikijs_host: "192.168.20.4"

#########################################################
# PostgreSQL admin system user
#########################################################

postgres_admin_user: "postgres"
postgres_ssh_user: "ubuntu"

wikijs_db_group: "db_master"
