beszel_install_dir: /opt/beszel

# Image custom
beszel_image_name: "beszel-custom:latest"

# Versions dynamiques
beszel_base_tag: "latest"
beszel_alpine_tag: "latest"

# Configuration Beszel
beszel_port: 8090
beszel_system_name: "beszel-Hub"

# Admin du Hub
beszel_admin_user: "admin"
beszel_admin_password: "ChangeMe123"

# Token agent (sera rempli automatiquement)
beszel_agent_token: ""

# URL interne du Hub (corrigé)
beszel_hub_url: "http://127.0.0.1:{{ beszel_port }}"


# Agent Beszel
beszel_agent_enabled: true

beszel_agent_data_dir: "/opt/beszel/agent_data"
beszel_agent_server: "http://127.0.0.1:8090"
beszel_agent_listen_port: "45876"
beszel_agent_key: "CHANGE_ME_PUBLIC_KEY"
beszel_agent_token: "CHANGE_ME_TOKEN"
beszel_agent_hub_url: "http://127.0.0.1:8090"
beszel_agent_system_name: "Beszel-Hub"



