---
# 3 - Créer le dossier Modoboa
- name: "3 - Créer le dossier Modoboa"
  file:
    path: "{{ modoboa_docker_dir }}"
    state: directory
    mode: '0755'

# 4 - Copier Dockerfile
- name: "4 - Copier Dockerfile"
  template:
    src: Dockerfile.j2
    dest: "{{ modoboa_docker_dir }}/Dockerfile"

# 5 - Copier entrypoint.sh
- name: "5 - Copier entrypoint.sh"
  template:
    src: entrypoint.sh.j2
    dest: "{{ modoboa_docker_dir }}/entrypoint.sh"
    mode: '0755'

# 6 - Copier docker-compose.yml
- name: "6 - Copier docker-compose.yml"
  template:
    src: docker-compose.yml.j2
    dest: "{{ modoboa_docker_dir }}/docker-compose.yml"

# 7 - Construire et lancer Modoboa
- name: "7 - Construire et lancer Modoboa"
  command:
    cmd: docker compose up -d --build
    chdir: "{{ modoboa_docker_dir }}"
