
services:
  beszel-server:
    image: henrygd/beszel
    container_name: beszel-server
    ports:
      - "8090:8090"
    volumes:
      - beszel-data:/data
    environment:
      - BESZEL_PORT=8090
      - SYSTEM_NAME=beszel-Hub
    restart: unless-stopped

volumes:
  beszel-data:
